//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAP_OPCEntities : DbContext
    {
        public SAP_OPCEntities()
            : base("name=SAP_OPCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_MauInPhieuNhapDetail> tbl_MauInPhieuNhapDetail { get; set; }
        public virtual DbSet<tbl_MauInPhieuNhapXuong> tbl_MauInPhieuNhapXuong { get; set; }
    }
}
