//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MauInPhieuNhapXuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_MauInPhieuNhapXuong()
        {
            this.tbl_MauInPhieuNhapDetail = new HashSet<tbl_MauInPhieuNhapDetail>();
        }
    
        public System.Guid Stt { get; set; }
        public string So_Ct { get; set; }
        public string Ngay_Ct { get; set; }
        public string Kho_Nhap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MauInPhieuNhapDetail> tbl_MauInPhieuNhapDetail { get; set; }
    }
}
