//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MauInPhieuNhapDetail
    {
        public System.Guid Stt { get; set; }
        public System.Guid Stt1 { get; set; }
        public string Ma_Vt { get; set; }
        public string Ten_Vt { get; set; }
        public string so_lo { get; set; }
        public decimal so_luong { get; set; }
        public string Dvt { get; set; }
        public string ghi_chu { get; set; }
        public string So_Ct { get; set; }
    
        public virtual tbl_MauInPhieuNhapXuong tbl_MauInPhieuNhapXuong { get; set; }
    }
}
